package ph.gov.dsr.performance.loadbalancer;

import lombok.Builder;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.Map;

/**
 * Represents a service instance in the load balancer
 */
@Data
@Builder
public class ServiceInstance {
    private String id;
    private String serviceName;
    private String host;
    private int port;
    private String protocol;
    private Map<String, String> metadata;
    private boolean healthy;
    private LocalDateTime lastHealthCheck;
    private LocalDateTime registeredAt;
    private int weight;
    private String zone;
    private String version;
    
    public String getBaseUrl() {
        return String.format("%s://%s:%d", 
            protocol != null ? protocol : "http", host, port);
    }
    
    public String getFullAddress() {
        return String.format("%s:%d", host, port);
    }
    
    public boolean isInSameZone(String targetZone) {
        return zone != null && zone.equals(targetZone);
    }
    
    public long getUptimeMinutes() {
        if (registeredAt == null) {
            return 0;
        }
        return java.time.Duration.between(registeredAt, LocalDateTime.now()).toMinutes();
    }
    
    public String getHealthStatus() {
        if (!healthy) {
            return "UNHEALTHY";
        }
        
        if (lastHealthCheck == null) {
            return "UNKNOWN";
        }
        
        long minutesSinceCheck = java.time.Duration.between(lastHealthCheck, LocalDateTime.now()).toMinutes();
        if (minutesSinceCheck > 5) {
            return "STALE";
        }
        
        return "HEALTHY";
    }
    
    public static ServiceInstanceBuilder builder() {
        return new ServiceInstanceBuilder();
    }
    
    public static class ServiceInstanceBuilder {
        private String protocol = "http";
        private int weight = 1;
        private boolean healthy = true;
        private LocalDateTime registeredAt = LocalDateTime.now();
        
        public ServiceInstanceBuilder protocol(String protocol) {
            this.protocol = protocol;
            return this;
        }
        
        public ServiceInstanceBuilder weight(int weight) {
            this.weight = weight;
            return this;
        }
        
        public ServiceInstanceBuilder healthy(boolean healthy) {
            this.healthy = healthy;
            return this;
        }
        
        public ServiceInstanceBuilder registeredAt(LocalDateTime registeredAt) {
            this.registeredAt = registeredAt;
            return this;
        }
        
        // Other builder methods would be generated by Lombok
    }
}
