# Philippine Dynamic Social Registry (DSR) - Registration Service
# No Database Configuration for Initial Deployment Testing
# Version: 1.0.0

server:
  port: ${REGISTRATION_SERVICE_PORT:8080}
  servlet:
    context-path: /
  shutdown: graceful

spring:
  application:
    name: dsr-registration-service

  # Disable database auto-configuration
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

  # Disable JPA auditing
  jpa:
    repositories:
      enabled: false

  # Cache Configuration
  cache:
    type: simple
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: ${REDIS_TIMEOUT:2000ms}
      lettuce:
        pool:
          max-active: ${REDIS_MAX_CONNECTIONS:8}
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE:health,info,metrics,prometheus}
  endpoint:
    health:
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:always}
  metrics:
    export:
      prometheus:
        enabled: ${METRICS_EXPORT_PROMETHEUS_ENABLED:true}

# Logging Configuration
logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    ph.gov.dsr: ${DSR_LOG_LEVEL:DEBUG}
    org.springframework: ${SPRING_LOG_LEVEL:INFO}
  pattern:
    console: ${LOG_CONSOLE_PATTERN:%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n}

# DSR Specific Configuration
dsr:
  registration:
    # Mock mode for testing
    mock-enabled: true
    
    # Validation Configuration
    validation:
      strict-mode: false
      skip-document-validation: true
      auto-approve: true
    
    # Processing Configuration
    processing:
      async-enabled: false
      batch-size: 50
      retry-attempts: 3
      retry-delay: 5000
    
    # Document Storage (Local filesystem)
    document-storage:
      type: ${DOCUMENT_STORAGE_TYPE:filesystem}
      path: ${DOCUMENT_STORAGE_PATH:./local-storage/documents}
      max-size: ${DOCUMENT_MAX_SIZE:10MB}
    
    # Notification Configuration
    notifications:
      sms:
        provider: ${SMS_PROVIDER:mock}
        enabled: ${FEATURE_SMS_NOTIFICATIONS:false}
      email:
        provider: ${EMAIL_PROVIDER:mock}
        enabled: ${FEATURE_EMAIL_NOTIFICATIONS:false}
      push:
        provider: ${PUSH_NOTIFICATION_PROVIDER:mock}
        enabled: ${FEATURE_PUSH_NOTIFICATIONS:false}

# Security Configuration
security:
  jwt:
    secret: ${JWT_SECRET:local_development_secret_key_change_in_production}
    expiration: ${JWT_EXPIRATION:86400}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800}

# Feature Flags
features:
  philsys-integration: false
  document-upload: true
  audit-logging: false
  analytics-collection: false
  database-persistence: false

# Local Development Specific
local:
  test-data:
    enabled: false
    auto-load: false
  
  mock-services:
    philsys:
      enabled: true
      port: ${MOCK_PHILSYS_PORT:9000}
      response-delay: ${MOCK_PHILSYS_RESPONSE_DELAY:1000}
  
  debug:
    enabled: true
    log-requests: true
    log-responses: true
