server:
  port: 8080

spring:
  application:
    name: dsr-data-management-service
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
