# Philippine Dynamic Social Registry (DSR) - Data Management Service
# Production Configuration
# Version: 3.0.0

server:
  port: ${DATA_MANAGEMENT_SERVICE_PORT:8082}
  servlet:
    context-path: /
  shutdown: graceful
  tomcat:
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 20000
    max-connections: 1000

spring:
  application:
    name: dsr-data-management-service
  
  # Database Configuration
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/dsr_db}
    username: ${DATABASE_USERNAME:dsr_user}
    password: ${DATABASE_PASSWORD:dsr_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

# Security Configuration
security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800}

# Logging Configuration
logging:
  level:
    ph.gov.dsr: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE_PATH:/var/log/dsr/data-management-service.log}
    max-size: ${LOG_FILE_MAX_SIZE:100MB}
    max-history: ${LOG_FILE_MAX_HISTORY:30}

# DSR Specific Configuration
dsr:
  # PhilSys Integration (Production)
  philsys:
    api-url: ${PHILSYS_API_URL:https://api.philsys.gov.ph/v1}
    api-key: ${PHILSYS_API_KEY}
    timeout: ${PHILSYS_TIMEOUT:30000}
    mock-enabled: ${MOCK_PHILSYS_ENABLED:false}
    retry-attempts: ${PHILSYS_RETRY_ATTEMPTS:3}
    circuit-breaker-enabled: ${PHILSYS_CIRCUIT_BREAKER:true}
  
  registration:
    # Validation Configuration
    validation:
      strict-mode: ${VALIDATION_STRICT_MODE:true}
      skip-document-validation: ${SKIP_DOCUMENT_VALIDATION:false}
      auto-approve: ${AUTO_APPROVE_REGISTRATIONS:false}
    
    # Processing Configuration
    processing:
      async-enabled: ${ASYNC_PROCESSING:true}
      batch-size: ${PROCESSING_BATCH_SIZE:100}
      retry-attempts: ${PROCESSING_RETRY_ATTEMPTS:3}
      retry-delay: ${PROCESSING_RETRY_DELAY:5000}
      max-concurrent-jobs: ${MAX_CONCURRENT_JOBS:10}
  
  # Data Management Configuration
  data-management:
    # Production mode - no mock implementations
    mock-enabled: false

    ingestion:
      max-file-size: ${MAX_FILE_SIZE:50MB}
      allowed-formats: ${ALLOWED_FORMATS:CSV,XLSX,JSON,XML}
      validation-enabled: ${VALIDATION_ENABLED:true}
      deduplication-enabled: ${DEDUPLICATION_ENABLED:true}

    archiving:
      retention-period-days: ${RETENTION_PERIOD:2555} # 7 years
      auto-archive-enabled: ${AUTO_ARCHIVE:true}
      archive-batch-size: ${ARCHIVE_BATCH_SIZE:1000}

    export:
      max-records-per-export: ${MAX_EXPORT_RECORDS:100000}
      export-formats: ${EXPORT_FORMATS:CSV,XLSX,JSON}
      encryption-enabled: ${EXPORT_ENCRYPTION:true}

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Feature Flags
features:
  philsys-integration: ${FEATURE_PHILSYS:true}
  document-upload: ${FEATURE_DOCUMENT_UPLOAD:true}
  audit-logging: ${FEATURE_AUDIT_LOGGING:true}
  analytics-collection: ${FEATURE_ANALYTICS:true}
  data-encryption: ${FEATURE_ENCRYPTION:true}

# Performance Configuration
performance:
  cache:
    enabled: ${CACHE_ENABLED:true}
    ttl-seconds: ${CACHE_TTL:3600}
  
  async:
    core-pool-size: ${ASYNC_CORE_POOL:5}
    max-pool-size: ${ASYNC_MAX_POOL:20}
    queue-capacity: ${ASYNC_QUEUE_CAPACITY:100}

# External Service Configuration
external-services:
  registration-service:
    url: ${REGISTRATION_SERVICE_URL:http://registration-service:8081}
    timeout: ${REGISTRATION_SERVICE_TIMEOUT:30000}
  
  eligibility-service:
    url: ${ELIGIBILITY_SERVICE_URL:http://eligibility-service:8083}
    timeout: ${ELIGIBILITY_SERVICE_TIMEOUT:30000}
  
  analytics-service:
    url: ${ANALYTICS_SERVICE_URL:http://analytics-service:8086}
    timeout: ${ANALYTICS_SERVICE_TIMEOUT:30000}
